@startuml
'https://plantuml.com/class-diagram
skinparam nodesep 20
skinparam ranksep 40
skinparam classAttributeIconSize 0
hide empty members
skinparam style strictuml
hide circle

abstract class InputStream {
    +{abstract}read():int
    +read(byte[] buf) : int
    +read(byte[] buf, int n, int ofs)
    +close()
}

class FileInputStream extends InputStream {
    +FileInputStream(name: String)
}

class ByteArrayInputStream extends InputStream {
    +ByteArrayInputStream(byte[])
}

@enduml